version: '2'

services:

  kirin:
    image: kirin:${KIRIN_TAG}
    restart: always
    env_file: kirin/kirin.env 
    volumes:
      - kirin_app:/usr/src/app
    ports:
     - "9090:9090"

  kirin_background:
    image: kirin:${KIRIN_TAG}
    restart: always
    depends_on:
      - kirin_configurator
    command: sh -c "while ! pg_isready -h kirin_database -d kirin -U navitia; do sleep 5; done; python ./manage.py load_realtime"
    env_file: kirin/kirin.env

  kirin_database:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER=navitia
      - POSTGRES_PASSWORD=navitia
      - POSTGRES_DB=kirin
    ports:
     - "9494:5432"

  kirin_configurator:
    image: kirin_configurator:${KIRIN_TAG}
    env_file: kirin/kirin.env
    working_dir: /usr/src/app
    depends_on:
      - "kirin_database"
    volumes_from:
      - kirin

  rabbitmq_kirin:
    image: rabbitmq:management

volumes:
  kirin_app:
